backend:
  name: git-gateway
  branch: main 

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "illustrations"
    label: "Illustrations"
    folder: "src/images/illustrations"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Alt Text", name: "alt", widget: "string" }
